[package]
name = "https-gateway"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "https_gateway"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build"]


[dependencies]
anchor-lang = "0.31.1"
sp1-solana = { git = "https://github.com/succinctlabs/sp1-solana" }
ark-bn254 = "0.4.0"  # For BN254 curve ops (used in Groth16)
hex = "0.4"



[profile.release]
lto = true
codegen-units = 1
opt-level = 3
strip = true



